name: Azure Login

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CLIENT_ID }}
        credsSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
