name: Terraform workflow run

on:
  push:
    branches: [main]
permissions:
  id-token: write
  contents: read
  issues: write
#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
env:
  ARM_CLIENT_ID: "${{ secrets.LUMADA_SAAS_AZ_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "970db9e0-469a-45ac-951e-e20574b2166c"
  ARM_TENANT_ID: "${{ secrets.LUMADA_SAAS_AZ_TENANT_ID }}"

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    env:
      #this is needed since we are running terraform with read-only permissions
      ARM_SKIP_PROVIDER_REGISTRATION: true
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of the Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
        
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.LUMADA_SAAS_AZ_CREDS }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
        terraform validate
        terraform plan
        terraform apply --auto-approve
